apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: hktp7krxm-go
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-go:5d05aa56eeb81ad519c4b14a9ebeac7f81f2204b@sha256:9aeedaba98a76dbd456953f5d5023b9800fd0880c610dce4bf764c64e642a107
          name: container-image
